export {
    setCustomers,
    setInputNameValue,
    setSelectedCompany,
    setActivity,
    setStatus,
    saveCustomerInformation,
    setSelectedDataTableOption,
    setSavedText,
    setIsAntModalVisible,
    updateCustomersDataGrid,
    getRandomQuotesRequest,
    getRandomQuotesFailure,
    getRandomQuotesSuccess,
    getAddressRequest,
    getAddressFailure,
    getAddressSuccess,
    getCoffeeRequest,
    getCoffeeFailure,
    getCoffeeSuccess
} from './form/formActions'
